# Generated by Django 5.0.3 on 2024-03-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_to_anywhere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
